collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.6510639
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#FDFAFB'
    - '#0E0D0C'
    - '#5C5D65'
    - '#88FBE9'
    - '#F278F2'
  rhythmicContrast: 0
layout_spectrum: 0.1531915
name: OliUclip
